#!/bin/sh


uci -q batch <<EOF
	set firewall.@zone[0].masq='1'
	add firewall zone
	set firewall.@zone[-1].name='lan'
	set firewall.@zone[-1].network='lan'
	set firewall.@zone[-1].input='ACCEPT'
	set firewall.@zone[-1].output='ACCEPT'
	set firewall.@zone[-1].forward='ACCEPT'


	add firewall zone
	set firewall.@zone[-1].name='wan2'
	set firewall.@zone[-1].network='wan2'
	set firewall.@zone[-1].input='ACCEPT'
	set firewall.@zone[-1].output='ACCEPT'
	set firewall.@zone[-1].forward='REJECT'
	set firewall.@zone[-1].mtu_fix='1'
	set firewall.@zone[-1].masq='1'

	add firewall forwarding
	set firewall.@forwarding[-1].src='lan'
	set firewall.@forwarding[-1].dest='wan'

	add firewall forwarding
	set firewall.@forwarding[-1].src='lan'
	set firewall.@forwarding[-1].dest='wan2'


	commit firewall

EOF

/etc/init.d/firewall restart
